### ISSUE TITLE
where can i get/generate/download the vocab pickle file?

### ISSUE THREAD

**Issue by josaphattirza** [ZhiGroup/Med-BERT#15]
I'm a researcher trying to reproduce the result of Med-BERT using dataset containing ICD-9 and ICD-10 codes. I am having trouble to generate the required vocab pickle file. Thank you for your help.

**Comment by lrasmy** [comment]
@josaphattirza 

In this version, if you do not have a predefined vocab pickled file, you just set that option to NA when you run [preprocess_pretrain_data.py](https://github.com/ZhiGroup/Med-BERT/blob/master/Pretraining%20Code/Data%20Pre-processing%20Code/preprocess_pretrain_data.py), and a new .types file will be generated (this is the vocab pickled dictionary) based on your data.

**Comment by josaphattirza** [comment]
Thank you
