### ISSUE TITLE
Fine tuning task: Predicting Diabetes patient risk to develop Heart Failure with Med-BERT

### ISSUE THREAD

**Issue by hikf3** [ZhiGroup/Med-BERT#17]
Can you please clarify after converting the pretrained model to Pytorch, is there any additional step?
I am not able to understand the input for the following in the fine tuning model definition.

> self.PreBERTmodel=BertForSequenceClassification.from_pretrained("pretrained_py_models/45M_chk"

)

The output of converting model from TenforFlow to Pytorch was a .bin file but the above code uses something different.

**Comment by lrasmy** [comment]
The path used is the path for the model folder containing both the model checkpoint (.bin) and the configuration file (config.json)
